name: Test and Build Reports Scheduler on Java 8

on: [push, pull_request]

env:
  OPENSEARCH_VERSION: '1.3.0-SNAPSHOT'

jobs:
  build:
    name: Test and Build on Java 8
    runs-on: ubuntu-latest
  
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Checkout Reports Scheduler
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: |
          cd reports-scheduler
          ./gradlew build -Dopensearch.version=${{ env.OPENSEARCH_VERSION }}

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Test with Java 8
        run: |
          cd reports-scheduler
          ./gradlew integTest -Dopensearch.version=${{ env.OPENSEARCH_VERSION }}

    
